on:
  push:
    branches:
      - main
name: build
jobs:
  
  build:
    name : build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
            dotnet-version: 8.0.x
             
      - name: Restore Dependencies
        run: dotnet restore
          
      - name: Download Dalamud
        # https://goatcorp.github.io/dalamud-distrib/latest.zip
        run: |
          Invoke-WebRequest -Uri  https://raw.githubusercontent.com/goatcorp/dalamud-distrib/f6fe5567488748319ec1e4b3ba45d4b8835f9525/latest.zip -OutFile latest.zip
          Expand-Archive -Force latest.zip "$env:AppData\XIVLauncher\addon\Hooks\dev"
                      
      - name: Build Plugin
        run: |
          invoke-expression 'dotnet build --no-restore --configuration Release QuestSolver'
           
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          path: .\QuestSolver\bin\Release\net8.0-windows\QuestSolver\
